"""update cpf_user

Revision ID: 43412eed60da
Revises: 82c1ce040b5b
Create Date: 2023-04-25 11:38:47.700592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43412eed60da'
down_revision = '82c1ce040b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('cpf_user',
               existing_type=sa.INTEGER(),
               type_=sa.Unicode(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('cpf_user',
               existing_type=sa.Unicode(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
