"""add field cpf to User model

Revision ID: 82c1ce040b5b
Revises: d4f293e41dfa
Create Date: 2023-04-24 15:06:43.628555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c1ce040b5b'
down_revision = 'd4f293e41dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_user', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cpf_user')

    # ### end Alembic commands ###
